use anyhow::{Context, Result};
use std::fmt::Write as FmtWrite;
use std::path::Path;
use std::process::Command;

use crate::config::WtreeConfig;
use crate::ports::PortAssignment;

/// Generate a standalone docker-compose.yml for a worktree slot.
/// Self-contained — does not depend on any base compose file.
/// Each service gets a unique container_name and slot-specific host ports.
pub fn generate_override(
    slug: &str,
    config: &WtreeConfig,
    ports: &PortAssignment,
    workspace_root: &Path,
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# Generated by branchyard — do not edit manually");
    let _ = writeln!(out, "# Slug: {slug}  Slot: {}", ports.slot);
    let _ = writeln!(out, "services:");

    for (i, svc) in config.services.iter().enumerate() {
        let host_port = ports.service_ports.get(i).copied().unwrap_or(svc.port);
        let _ = writeln!(out, "  {}:", svc.name);
        if let Some(build_ctx) = &svc.build {
            let resolved = workspace_root.join(build_ctx);
            let _ = writeln!(out, "    build: {}", resolved.display());
        }
        let _ = writeln!(out, "    image: {}", svc.image);
        let _ = writeln!(out, "    container_name: {slug}-{}", svc.name);
        if let Some(platform) = &svc.platform {
            let _ = writeln!(out, "    platform: {platform}");
        }
        if let Some(cmd) = &svc.command {
            let _ = writeln!(out, "    command: {cmd}");
        }
        if svc.port > 0 {
            let _ = writeln!(out, "    ports:");
            let _ = writeln!(out, "      - \"{host_port}:{}\"", svc.port);
        }
        if !svc.environment.is_empty() {
            let _ = writeln!(out, "    environment:");
            for env in &svc.environment {
                let _ = writeln!(out, "      - {env}");
            }
        }
        if let Some(env_file) = &svc.env_file {
            // Resolve env_file relative to workspace root so Docker can find it
            // regardless of where the compose file lives.
            let resolved = workspace_root.join(env_file);
            let _ = writeln!(out, "    env_file:");
            let _ = writeln!(out, "      - {}", resolved.display());
        }
        if !svc.volumes.is_empty() {
            let _ = writeln!(out, "    volumes:");
            for vol in &svc.volumes {
                let _ = writeln!(out, "      - {vol}");
            }
        }
        if !svc.depends_on.is_empty() {
            let _ = writeln!(out, "    depends_on:");
            for dep in &svc.depends_on {
                let _ = writeln!(out, "      - {dep}");
            }
        }
    }

    // Collect named volumes declared in service volume mounts
    let named_volumes: Vec<&str> = config
        .services
        .iter()
        .flat_map(|s| s.volumes.iter())
        .filter_map(|v| {
            let part = v.split(':').next()?;
            // Named volumes don't start with / or .
            if !part.starts_with('/') && !part.starts_with('.') {
                Some(part)
            } else {
                None
            }
        })
        .collect::<std::collections::HashSet<_>>()
        .into_iter()
        .collect();

    if !named_volumes.is_empty() {
        let _ = writeln!(out, "volumes:");
        let mut sorted = named_volumes;
        sorted.sort();
        for vol in sorted {
            let _ = writeln!(out, "  {vol}:");
        }
    }

    out
}

pub fn write_override(dir: &Path, content: &str) -> Result<()> {
    let path = dir.join("docker-compose.override.yml");
    std::fs::write(&path, content).with_context(|| format!("Failed to write {}", path.display()))
}

pub fn up(slug: &str, slug_dir: &Path) -> Result<()> {
    let compose_file = slug_dir.join("docker-compose.override.yml");
    let status = Command::new("docker")
        .args([
            "compose",
            "-p",
            slug,
            "-f",
            compose_file.to_str().unwrap(),
            "up",
            "-d",
        ])
        .status()
        .context("Failed to run docker compose up")?;

    if !status.success() {
        anyhow::bail!("docker compose up failed");
    }
    Ok(())
}

pub fn down(slug: &str, slug_dir: &Path) -> Result<()> {
    let compose_file = slug_dir.join("docker-compose.override.yml");
    let status = Command::new("docker")
        .args([
            "compose",
            "-p",
            slug,
            "-f",
            compose_file.to_str().unwrap(),
            "down",
        ])
        .status()
        .context("Failed to run docker compose down")?;

    if !status.success() {
        anyhow::bail!("docker compose down failed");
    }
    Ok(())
}
