//! Ghostty terminal integration.
//!
//! Ghostty does not have a native "launch config" format yet (as of 2026).
//! This integration generates a shell script that opens Ghostty with one
//! window per repo, each in its own working directory.
//!
//! The script is written to: ~/.config/ghostty/branchyard-<slug>.sh
//! It is executed once and then left on disk for the user to re-run if needed.
//!
//! Requires: Ghostty installed and the `ghostty` binary on $PATH.

use anyhow::Result;
use std::collections::HashMap;
use std::fmt::Write as FmtWrite;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::Command;

use crate::config::WtreeConfig;
use crate::ports::{interpolate, PortAssignment};
use crate::terminal::TerminalIntegration;

pub struct Ghostty;

impl TerminalIntegration for Ghostty {
    fn open(
        &self,
        slug: &str,
        config: &WtreeConfig,
        worktree_base: &Path,
        ports: &PortAssignment,
        vars: &HashMap<String, String>,
    ) -> Result<()> {
        let script = generate(slug, config, worktree_base, ports, vars);
        let path = script_path(slug);
        std::fs::create_dir_all(
            path.parent()
                .expect("config path always has a parent directory"),
        )?;
        std::fs::write(&path, &script)?;
        // Make executable
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))?;
        // Execute the script
        Command::new("sh").arg(&path).status().ok();
        Ok(())
    }

    fn remove(&self, slug: &str) -> Result<()> {
        let path = script_path(slug);
        if path.exists() {
            std::fs::remove_file(path)?;
        }
        Ok(())
    }
}

fn script_path(slug: &str) -> std::path::PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| std::path::PathBuf::from("."))
        .join(".config")
        .join("ghostty")
        .join(format!("branchyard-{slug}.sh"))
}

fn generate(
    slug: &str,
    config: &WtreeConfig,
    worktree_base: &Path,
    ports: &PortAssignment,
    vars: &HashMap<String, String>,
) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "#!/bin/sh");
    let _ = writeln!(out, "# Generated by branchyard — worktree: {slug}");
    let _ = writeln!(out);

    for (i, repo) in config.repos.iter().enumerate() {
        let path = worktree_base.join(slug).join(&repo.name);

        let cmd_part = match &repo.commands.serve {
            Some(serve_cmd) => {
                let mut repo_vars = vars.clone();
                if let Some(&port) = ports.repo_ports.get(i) {
                    repo_vars.insert("port".to_string(), port.to_string());
                }
                let cmd = interpolate(serve_cmd, &repo_vars);
                format!(" -e \"cd {} && {}\"", path.display(), cmd)
            }
            None => format!(" -e \"cd {}\"", path.display()),
        };

        let _ = writeln!(out, "ghostty{cmd_part} &");
    }

    let _ = writeln!(out, "wait");
    out
}
